import random
import time


print("🗲"*30)
print("Bem-vindos ao jogo de Pedra, Papel e Tesoura!")
print("🗲"*30)



print("Qual sua jogada?")
print ("(1) Pedra (2) Papel (3) Tesoura")
while True:
        rodada_do_jogador = (int(input("Escolha sua arma: ")))
        if rodada_do_jogador <4 and rodada_do_jogador >0:
            break
        elif rodada_do_jogador >4 or rodada_do_jogador <0:
            print ("Tente novamente")
rodada_do_computador = random.randrange(1,4)
if rodada_do_jogador == 1 and rodada_do_computador == 1:
            time.sleep(2)
            print("Sua jogada foi pedra ◇")
            time.sleep(2)
            print("O computador jogou pedra ◇")
            time.sleep(2)
            print("empate, jogue novamente")
            time.sleep(2)
            print(" ")
            time.sleep(2)
elif rodada_do_jogador == 1 and rodada_do_computador == 2:
            time.sleep(2)
            print ("Você jogou pedra ◇")
            time.sleep(2)
            print ("O computador jogou papel ✉")
            time.sleep(2)
            print ("Você foi coberto pela pedra")
            time.sleep(1)
            print ("fim do jogo")
            time.sleep(2)
            print(" ")
            time.sleep(2)
elif rodada_do_jogador == 1 and rodada_do_computador == 3:
            time.sleep(2)
            print ("Você jogou pedra ◇")
            time.sleep(2)
            print ("O computador jogou tesoura ✃")
            time.sleep(2)
            print ("Você destruiu a tesoura, ganhaste! :D")
            time.sleep(2)
            print(" ")
            time.sleep(2)
if rodada_do_jogador == 2 and rodada_do_computador == 2:
            time.sleep(2)
            print ("Você jogou papel ✉")
            time.sleep(2)
            print ("O computador jogou papel ✉")
            time.sleep(2)
            print ("Houve empate, tente novamente")
            time.sleep(2)
            print(" ")
            time.sleep(2)
elif rodada_do_jogador == 2 and rodada_do_computador == 1:
            time.sleep(2)
            print ("Você jogou papel ✉")
            time.sleep(2)
            print ("O computador jogou pedra ◇")
            time.sleep(2)
            print ("você cobriu a pedra, ganhaste! :D")
            time.sleep(2)
            print(" ")
            time.sleep(2)
elif rodada_do_jogador == 2 and rodada_do_computador == 3:
        time.sleep(2)
        print ("Você jogou papel ✉")
        time.sleep(2)
        print ("O computador jogou tesoura ✃")
        time.sleep(2)
        print ("Você foi cortado")
        time.sleep(1)
        print ("Fim do jogo")
        time.sleep(2)
        print(" ")
        time.sleep(2)
if rodada_do_jogador == 3 and rodada_do_computador == 3:
        time.sleep(2)
        print ("Você jogou tesoura ✃")
        time.sleep(2)
        print ("O computador jogou tesoura ✃")
        time.sleep(1)
        print ("Alerta de empate. Jogue de novo")
        time.sleep(2)
        print(" ")
        time.sleep(2)
elif rodada_do_jogador == 3 and rodada_do_computador == 1:
        time.sleep(2)
        print ("Você jogou tesoura ✃")
        time.sleep(2)
        print ("O computador jogou pedra ◇")
        time.sleep(2)
        print("Você foi destruído")
        time.sleep(1)
        print("Fim do Jogo")
        time.sleep(2)
        print(" ")
        time.sleep(2)
elif rodada_do_jogador == 3 and rodada_do_computador == 2:
        time.sleep(2)
        print ("Você jogou tesoura ✃")
        time.sleep(2)
        print ("O computador jogou papel ✉")
        time.sleep(2)
        print ("Você cortou o papel, ganhaste :D")
        time.sleep(2)
        print(" ")
        time.sleep(2)


def pergunta ():
    print("Qual sua jogada?")
    print ("(1) Pedra (2) Papel (3) Tesoura")
    while True:
            rodada_do_jogador = (int(input("Escolha sua arma: ")))
            if rodada_do_jogador <4 and rodada_do_jogador >0:
                break
            elif rodada_do_jogador >4 or rodada_do_jogador <0:
                print ("Tente novamente")
    rodada_do_computador = random.randrange(1,4)
    if rodada_do_jogador == 1 and rodada_do_computador == 1:
                time.sleep(2)
                print("Sua jogada foi pedra ◇")
                time.sleep(2)
                print("O computador jogou pedra ◇")
                time.sleep(2)
                print("empate, jogue novamente")
                time.sleep(2)
                print(" ")
                time.sleep(2)
    elif rodada_do_jogador == 1 and rodada_do_computador == 2:
                time.sleep(2)
                print ("Você jogou pedra ◇")
                time.sleep(2)
                print ("O computador jogou papel ✉")
                time.sleep(2)
                print ("Você foi coberto pela pedra")
                time.sleep(1)
                print ("fim do jogo")
                time.sleep(2)
                print(" ")
                time.sleep(2)
    elif rodada_do_jogador == 1 and rodada_do_computador == 3:
                time.sleep(2)
                print ("Você jogou pedra ◇")
                time.sleep(2)
                print ("O computador jogou tesoura ✃")
                time.sleep(2)
                print ("Você destruiu a tesoura, ganhaste! :D")
                time.sleep(2)
                print(" ")
                time.sleep(2)
    if rodada_do_jogador == 2 and rodada_do_computador == 2:
                time.sleep(2)
                print ("Você jogou papel ✉")
                time.sleep(2)
                print ("O computador jogou papel ✉")
                time.sleep(2)
                print ("Houve empate, tente novamente")
                time.sleep(2)
                print(" ")
                time.sleep(2)
    elif rodada_do_jogador == 2 and rodada_do_computador == 1:
                time.sleep(2)
                print ("Você jogou papel ✉")
                time.sleep(2)
                print ("O computador jogou pedra ◇")
                time.sleep(2)
                print ("você cobriu a pedra, ganhaste! :D")
                time.sleep(2)
                print(" ")
                time.sleep(2)
    elif rodada_do_jogador == 2 and rodada_do_computador == 3:
            time.sleep(2)
            print ("Você jogou papel ✉")
            time.sleep(2)
            print ("O computador jogou tesoura ✃")
            time.sleep(2)
            print ("Você foi cortado")
            time.sleep(1)
            print ("Fim do jogo")
            time.sleep(2)
            print(" ")
            time.sleep(2)
    if rodada_do_jogador == 3 and rodada_do_computador == 3:
            time.sleep(2)
            print ("Você jogou tesoura ✃")
            time.sleep(2)
            print ("O computador jogou tesoura ✃")
            time.sleep(1)
            print ("Alerta de empate. Jogue de novo")
            time.sleep(2)
            print(" ")
            time.sleep(2)
    elif rodada_do_jogador == 3 and rodada_do_computador == 1:
            time.sleep(2)
            print ("Você jogou tesoura ✃")
            time.sleep(2)
            print ("O computador jogou pedra ◇")
            time.sleep(2)
            print("Você foi destruído")
            time.sleep(1)
            print("Fim do Jogo")
            time.sleep(2)
            print(" ")
            time.sleep(2)
    elif rodada_do_jogador == 3 and rodada_do_computador == 2:
            time.sleep(2)
            print ("Você jogou tesoura ✃")
            time.sleep(2)
            print ("O computador jogou papel ✉")
            time.sleep(2)
            print ("Você cortou o papel, ganhaste :D")
            time.sleep(2)
            print (" ")
            time.sleep(2)

while True:
    empate = rodada_do_computador == rodada_do_jogador
    if empate:
        pergunta ()
    break 

print ("Gostaria de jogar novamente?")
print ("(1) Sim ou (2) Não??")
time.sleep(1)
resposta = int(input("Hein? "))
while True:
    if resposta == 1:
        pergunta ()
        print ("Gostaria de jogar novamente?")
        print ("(1) Sim ou (2) Não??")
        time.sleep(1)
        resposta = int(input("Hein? "))
    elif resposta == 2:
        print ("Até a Próxima ;)")
        break
        time.sleep(2)

